apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Saved search query runner / notification service.
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: query-runner
  name: query-runner
spec:
  minReadySeconds: 10
  replicas: {{ .Values.queryRunner.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: query-runner
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: query-runner
    spec:
      containers:
      - name: query-runner
        image: {{ include "queryRunner.container" . }}
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 3183
          name: http
        resources:
        {{- if .Values.queryRunner.resources.requests }}
          requests:
        {{- range $key, $val := .Values.queryRunner.resources.requests }}
            {{ $key }}: {{ $val }}
        {{- end }}
        {{- end }}
        {{- if .Values.queryRunner.resources.limits }}
          limits:
        {{- range $key, $val := .Values.queryRunner.resources.limits }}
            {{ $key }}: {{ $val }}
        {{- end }}
        {{- end }}
      {{ include "jaegerAgent.spec" . | indent 6 }}
      securityContext:
        runAsUser: 0
