apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Code Insights TimescaleDB instance.
  labels:
    app.kubernetes.io/component: codeinsights-db
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: codeinsights-db
spec:
  minReadySeconds: 10
  replicas: {{ .Values.codeinsigtsdb.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: codeinsights-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: codeinsights-db
        group: backend
    spec:
      containers:
      - name: timescaledb
        image: {{ include "codeinsigtsdb.container" . }}
        env:
        - name: POSTGRES_PASSWORD # Accessible by Sourcegraph applications on the network only, so password auth is not used.
          value: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 5432
          name: timescaledb
        resources:
        {{- if .Values.codeinsigtsdb.resources.requests }}
          requests:
        {{- range $key, $val := .Values.codeinsigtsdb.resources.requests }}
            {{ $key }}: {{ $val }}
        {{- end }}
        {{- end }}
        {{- if .Values.codeinsigtsdb.resources.limits }}
          limits:
        {{- range $key, $val := .Values.codeinsigtsdb.resources.limits }}
            {{ $key }}: {{ $val }}
        {{- end }}
        {{- end }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: disk
        - mountPath: /conf
          name: timescaledb-conf
      # - env:
      #   - name: DATA_SOURCE_NAME
      #     value: postgres://sg:@localhost:5432/?sslmode=disable
      #   # Dax: Temporarily switch back to upstream postgres exporter
      #   # https://github.com/sourcegraph/sourcegraph/issues/18225
      #   image: wrouesnel/postgres_exporter:v0.7.0@sha256:785c919627c06f540d515aac88b7966f352403f73e931e70dc2cbf783146a98b
      #   terminationMessagePolicy: FallbackToLogsOnError
      #   name: pgsql-exporter
      #   resources:
      #     limits:
      #       cpu: 10m
      #       memory: 50Mi
      #     requests:
      #       cpu: 10m
      #       memory: 50Mi
      securityContext:
        runAsUser: 0
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: codeinsights-db
      - name: timescaledb-conf
        configMap:
          defaultMode: 0777
          name: codeinsights-db-conf
